id = "clean-vscode-icons"
name = "Clean VSCode Icons Theme"
version = "0.1.1"
schema_version = 1
authors = [
    "Jacobtread <jacobtread@gmail.com>",
    "Mhammed Talhaouy (talhaouycoding@gmail.com)",
]
description = "Icon theme for Zed packed with icons for many extensions and folders"
repository = "https://github.com/jacobtread/clean-vscode-icons"
