id = "vscode-icons"
name = "VSCode Icons Theme"
version = "0.1.0"
schema_version = 1
authors = [
    "Jacobtread <jacobtread@gmail.com>",
    "Mhammed Talhaouy (talhaouycoding@gmail.com)",
]
description = "Icon theme for Zed"
repository = "https://github.com/jacobtread/zed-vscode-icons"
